---
- hosts: haproxy
  gather_facts: true

- hosts: haproxy
  tasks:
    - name: Uninstalls Apache
      become: yes
      apt:
        pkg: ["apache2", "libapache2-mod-php"]
        state: absent
        update_cache: true

    - name: Installing haproxy load balancer
      become: yes
      apt:
        pkg: ["haproxy", "unzip"]
        state: present
        update_cache: true

    - name: Pushes configuration
      become: yes
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: 0640
        owner: root
        group: root
      notify:
        - restart haproxy

    - name: Sets default starting flag to 1
      become: yes
      lineinfile:
        dest: /etc/default/haproxy
        regexp: "^ENABLED"
        line: "ENABLED=1"
      notify:
        - restart haproxy

  handlers:
    - name: restart haproxy
      become: yes
      service:
        name: haproxy
        state: restarted
